import { IMPORT_FORMATS, api, newId } from '@coral/shared'
import { sql } from 'drizzle-orm'
import {
  type AnyPgColumn,
  bigint,
  boolean,
  check,
  index,
  integer,
  jsonb,
  numeric,
  pgTable,
  primaryKey,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from 'drizzle-orm/pg-core'

/**
 * Phase 1 schema (data-model.md). Column names are snake_case (casing: 'snake_case', D12);
 * ids are UUID v7 generated by the application (D11). Every business table has tenant_id (P5);
 * tenants, users and refresh_tokens are the global identity tables (D10).
 */

const id = () => uuid().primaryKey().$defaultFn(newId)
const createdAt = () => timestamp({ withTimezone: true }).notNull().defaultNow()
const tenantId = () =>
  uuid()
    .notNull()
    .references(() => tenants.id)

const quoted = (values: readonly string[]) => values.map((v) => `'${v}'`).join(', ')

function oneOf(column: string, values: readonly string[]) {
  return sql.raw(`${column} in (${quoted(values)})`)
}

/** A nullable column holds null or one of `values`. */
function nullOrOneOf(column: string, values: readonly string[]) {
  return sql.raw(`${column} is null or ${column} in (${quoted(values)})`)
}

/** Every element of a text[] column is one of `values`. */
function allOf(column: string, values: readonly string[]) {
  return sql.raw(`${column} <@ array[${quoted(values)}]::text[]`)
}

/** Money in USD: 6 decimals keep the cost of one cheap call. */
const usd = () => numeric({ precision: 14, scale: 6, mode: 'number' }).notNull().default(0)
const emptyArray = () =>
  text()
    .array()
    .notNull()
    .default(sql`'{}'::text[]`)

// ---- identity (global) -----------------------------------------------------------------------------

export const tenants = pgTable('tenants', {
  id: id(),
  name: text().notNull(),
  plan: text().notNull().default('dev'),
  settings: jsonb().notNull().default({}),
  createdAt: createdAt(),
})

export const users = pgTable(
  'users',
  {
    id: id(),
    email: text().notNull(),
    passwordHash: text().notNull(),
    name: text().notNull(),
    createdAt: createdAt(),
  },
  (t) => [
    uniqueIndex().on(t.email),
    check('users_email_lowercase', sql`${t.email} = lower(${t.email})`),
  ],
)

export const ROLES = ['owner', 'admin', 'member', 'viewer'] as const

export const memberships = pgTable(
  'memberships',
  {
    tenantId: tenantId(),
    userId: uuid()
      .notNull()
      .references(() => users.id),
    role: text({ enum: ROLES }).notNull(),
    createdAt: createdAt(),
  },
  (t) => [
    primaryKey({ columns: [t.tenantId, t.userId] }),
    check('memberships_role', oneOf('role', ROLES)),
  ],
)

export const refreshTokens = pgTable(
  'refresh_tokens',
  {
    id: id(),
    userId: uuid()
      .notNull()
      .references(() => users.id),
    tokenHash: text().notNull(),
    expiresAt: timestamp({ withTimezone: true }).notNull(),
    revokedAt: timestamp({ withTimezone: true }),
    replacedBy: uuid(),
    createdAt: createdAt(),
  },
  (t) => [uniqueIndex().on(t.tokenHash)],
)

// ---- business tables --------------------------------------------------------------------------------

export const projects = pgTable(
  'projects',
  {
    id: id(),
    tenantId: tenantId(),
    name: text().notNull(),
    gitRepoPath: text().notNull(),
    createdAt: createdAt(),
  },
  (t) => [uniqueIndex().on(t.tenantId, t.name)],
)

export const apps = pgTable(
  'apps',
  {
    id: id(),
    tenantId: tenantId(),
    projectId: uuid()
      .notNull()
      .references(() => projects.id),
    platform: text({ enum: ['android', 'ios'] }).notNull(),
    packageOrBundleId: text().notNull(),
    name: text().notNull(),
    createdAt: createdAt(),
  },
  (t) => [
    uniqueIndex().on(t.projectId, t.platform, t.packageOrBundleId),
    check('apps_platform', oneOf('platform', ['android', 'ios'])),
  ],
)

export const builds = pgTable(
  'builds',
  {
    id: id(),
    tenantId: tenantId(),
    appId: uuid()
      .notNull()
      .references(() => apps.id),
    version: text().notNull(),
    artifactKey: text().notNull(),
    checksumSha256: text().notNull(),
    sizeBytes: bigint({ mode: 'number' }).notNull(),
    uploadedBy: uuid().references(() => users.id),
    createdAt: createdAt(),
  },
  (t) => [index().on(t.appId, t.createdAt.desc())],
)

export const AGENT_STATUSES = ['online', 'offline', 'revoked'] as const

export const agents = pgTable(
  'agents',
  {
    id: id(),
    tenantId: tenantId(),
    name: text().notNull(),
    tokenHash: text().notNull(),
    os: text(),
    version: text(),
    capabilities: jsonb().notNull().default({}),
    status: text({ enum: AGENT_STATUSES }).notNull().default('offline'),
    lastSeenAt: timestamp({ withTimezone: true }),
    revokedAt: timestamp({ withTimezone: true }),
    createdAt: createdAt(),
  },
  (t) => [uniqueIndex().on(t.tokenHash), check('agents_status', oneOf('status', AGENT_STATUSES))],
)

export const DEVICE_KINDS = ['real', 'emulator', 'simulator'] as const
export const DEVICE_STATUSES = ['idle', 'leased', 'offline'] as const

export const devices = pgTable(
  'devices',
  {
    id: id(),
    tenantId: tenantId(),
    agentId: uuid()
      .notNull()
      .references(() => agents.id),
    platform: text({ enum: ['android', 'ios'] }).notNull(),
    kind: text({ enum: DEVICE_KINDS }).notNull(),
    model: text().notNull(),
    osVersion: text().notNull(),
    apiLevel: integer(),
    udid: text().notNull(),
    status: text({ enum: DEVICE_STATUSES }).notNull().default('offline'),
    lastSeenAt: timestamp({ withTimezone: true }),
    createdAt: createdAt(),
  },
  (t) => [
    uniqueIndex().on(t.agentId, t.udid),
    check('devices_kind', oneOf('kind', DEVICE_KINDS)),
    check('devices_status', oneOf('status', DEVICE_STATUSES)),
  ],
)

export const LEASE_KINDS = ['run', 'exploration', 'live', 'recording'] as const
export const LEASE_RELEASE_REASONS = [
  'done',
  'cancelled',
  'timeout',
  'agent_offline',
  'ack_timeout',
  // Phase 2: a person let go of the device, or a recording took over their control session.
  'released',
  'replaced_by_recording',
] as const

export const leases = pgTable(
  'leases',
  {
    id: id(),
    tenantId: tenantId(),
    deviceId: uuid()
      .notNull()
      .references(() => devices.id),
    kind: text({ enum: LEASE_KINDS }).notNull(),
    holderRef: text().notNull(),
    acquiredAt: createdAt(),
    expiresAt: timestamp({ withTimezone: true }).notNull(),
    releasedAt: timestamp({ withTimezone: true }),
    releaseReason: text({ enum: LEASE_RELEASE_REASONS }),
  },
  (t) => [
    // At most one open lease per device (D16, SC-007).
    uniqueIndex('leases_one_open_per_device')
      .on(t.deviceId)
      .where(sql`${t.releasedAt} is null`),
    check('leases_kind', oneOf('kind', LEASE_KINDS)),
    check(
      'leases_release_reason',
      sql`release_reason is null or ${oneOf('release_reason', LEASE_RELEASE_REASONS)}`,
    ),
  ],
)

export const TEST_CASE_STATUSES = api.TEST_CASE_STATUSES
export const TEST_CASE_SOURCES = api.TEST_CASE_SOURCES

export const testCases = pgTable(
  'test_cases',
  {
    id: id(),
    tenantId: tenantId(),
    projectId: uuid()
      .notNull()
      .references(() => projects.id),
    slug: text().notNull(),
    pathInRepo: text().notNull(),
    intent: text().notNull(),
    tags: text()
      .array()
      .notNull()
      .default(sql`'{}'::text[]`),
    platforms: text().array().notNull(),
    status: text({ enum: TEST_CASE_STATUSES }).notNull().default('draft'),
    headCommit: text().notNull(),
    source: text({ enum: TEST_CASE_SOURCES }).notNull().default('manual'),
    sourceRef: text(),
    // Phase 3 (D41): the validation runs of an AI-written test case and why it stays a draft.
    validation: jsonb().$type<api.TestCaseValidation>(),
    draftReason: text({ enum: api.DRAFT_REASONS }),
    flags: emptyArray().$type<api.TestCaseFlag[]>(),
    validatedAt: timestamp({ withTimezone: true }),
    updatedBy: uuid().references(() => users.id),
    createdAt: createdAt(),
    updatedAt: timestamp({ withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex().on(t.projectId, t.slug),
    check('test_cases_status', oneOf('status', TEST_CASE_STATUSES)),
    check('test_cases_source', oneOf('source', TEST_CASE_SOURCES)),
    check('test_cases_draft_reason', nullOrOneOf('draft_reason', api.DRAFT_REASONS)),
    check('test_cases_flags', allOf('flags', api.TEST_CASE_FLAGS)),
  ],
)

export const PROJECT_FILE_KINDS = ['popups'] as const

export const projectFiles = pgTable(
  'project_files',
  {
    tenantId: tenantId(),
    projectId: uuid()
      .notNull()
      .references(() => projects.id),
    kind: text({ enum: PROJECT_FILE_KINDS }).notNull(),
    pathInRepo: text().notNull(),
    headCommit: text().notNull(),
    updatedAt: timestamp({ withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    primaryKey({ columns: [t.projectId, t.kind] }),
    check('project_files_kind', oneOf('kind', PROJECT_FILE_KINDS)),
  ],
)

export const RUN_STATUSES = ['queued', 'running', 'passed', 'failed', 'cancelled', 'error'] as const
export const RUN_TRIGGERS = ['manual', 'schedule', 'ci', 'validation'] as const

export const runs = pgTable(
  'runs',
  {
    id: id(),
    tenantId: tenantId(),
    projectId: uuid()
      .notNull()
      .references(() => projects.id),
    buildId: uuid()
      .notNull()
      .references(() => builds.id),
    deviceId: uuid()
      .notNull()
      .references(() => devices.id),
    trigger: text({ enum: RUN_TRIGGERS }).notNull().default('manual'),
    status: text({ enum: RUN_STATUSES }).notNull().default('queued'),
    failureCode: text(),
    popupsCommit: text().notNull(),
    // Phase 3: the AI-written test case a `validation` run checks (FR-030).
    validationOf: uuid().references(() => testCases.id),
    queuedAt: createdAt(),
    startedAt: timestamp({ withTimezone: true }),
    finishedAt: timestamp({ withTimezone: true }),
    createdBy: uuid().references(() => users.id),
  },
  (t) => [
    index().on(t.tenantId, t.queuedAt.desc()),
    check('runs_status', oneOf('status', RUN_STATUSES)),
    check('runs_trigger', oneOf('trigger', RUN_TRIGGERS)),
  ],
)

export const RUN_ITEM_STATUSES = [
  'pending',
  'running',
  'passed',
  'failed',
  'skipped',
  'error',
] as const

export const runItems = pgTable(
  'run_items',
  {
    id: id(),
    tenantId: tenantId(),
    runId: uuid()
      .notNull()
      .references(() => runs.id, { onDelete: 'cascade' }),
    testCaseId: uuid()
      .notNull()
      .references(() => testCases.id),
    commit: text().notNull(),
    position: integer().notNull(),
    status: text({ enum: RUN_ITEM_STATUSES }).notNull().default('pending'),
    failureCode: text(),
    failedStepId: text(),
    startedAt: timestamp({ withTimezone: true }),
    finishedAt: timestamp({ withTimezone: true }),
  },
  (t) => [
    uniqueIndex().on(t.runId, t.position),
    check('run_items_status', oneOf('status', RUN_ITEM_STATUSES)),
  ],
)

export const runSteps = pgTable(
  'run_steps',
  {
    id: id(),
    tenantId: tenantId(),
    runItemId: uuid()
      .notNull()
      .references(() => runItems.id, { onDelete: 'cascade' }),
    stepIndex: integer().notNull(),
    stepId: text().notNull(),
    action: text().notNull(),
    status: text({ enum: ['passed', 'failed'] }).notNull(),
    locatorUsedIndex: integer(),
    degraded: boolean().notNull().default(false),
    unstable: boolean().notNull().default(false),
    durationMs: integer().notNull(),
    failureCode: text(),
    message: text(),
    popupsHandled: jsonb().notNull().default([]),
    artifactPrefix: text().notNull(),
    finishedAt: timestamp({ withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex().on(t.runItemId, t.stepIndex),
    check('run_steps_status', oneOf('status', ['passed', 'failed'])),
  ],
)

export const auditLog = pgTable(
  'audit_log',
  {
    id: id(),
    tenantId: tenantId(),
    actor: text().notNull(),
    action: text().notNull(),
    target: text(),
    meta: jsonb().notNull().default({}),
    createdAt: createdAt(),
  },
  (t) => [index().on(t.tenantId, t.createdAt.desc())],
)

// ---- Phase 2: live control and the Recorder (specs/003-phase-2-web-recorder/data-model.md) --------

export const LIVE_END_REASONS = [
  'released',
  'idle_timeout',
  'agent_offline',
  'replaced_by_recording',
] as const

/** A person holding a device from the browser (lease kind `live`, research R7). */
export const liveSessions = pgTable(
  'live_sessions',
  {
    id: id(),
    tenantId: tenantId(),
    deviceId: uuid()
      .notNull()
      .references(() => devices.id),
    userId: uuid()
      .notNull()
      .references(() => users.id),
    leaseId: uuid()
      .notNull()
      .references(() => leases.id),
    startedAt: createdAt(),
    lastCommandAt: timestamp({ withTimezone: true }).notNull().defaultNow(),
    endedAt: timestamp({ withTimezone: true }),
    endReason: text({ enum: LIVE_END_REASONS }),
  },
  (t) => [
    uniqueIndex('live_sessions_one_open_per_device')
      .on(t.deviceId)
      .where(sql`${t.endedAt} is null`),
    check(
      'live_sessions_end_reason',
      sql`end_reason is null or ${oneOf('end_reason', LIVE_END_REASONS)}`,
    ),
  ],
)

export const RECORDING_STATUSES = ['recording', 'stopped', 'saved', 'discarded', 'expired'] as const

/** A recording in progress (research R10): draft steps with snapshots, not yet a test case. */
export const recordings = pgTable(
  'recordings',
  {
    id: id(),
    tenantId: tenantId(),
    projectId: uuid()
      .notNull()
      .references(() => projects.id),
    appId: uuid()
      .notNull()
      .references(() => apps.id),
    buildId: uuid()
      .notNull()
      .references(() => builds.id),
    deviceId: uuid()
      .notNull()
      .references(() => devices.id),
    userId: uuid()
      .notNull()
      .references(() => users.id),
    // Null once stopped: the device is free again, the recording can still be edited and saved.
    leaseId: uuid().references(() => leases.id),
    status: text({ enum: RECORDING_STATUSES }).notNull().default('recording'),
    steps: jsonb().notNull().default([]),
    intent: text().notNull().default(''),
    slug: text().notNull(),
    testCaseId: uuid().references(() => testCases.id),
    createdAt: createdAt(),
    updatedAt: timestamp({ withTimezone: true }).notNull().defaultNow(),
    savedAt: timestamp({ withTimezone: true }),
    // updated_at + 7 days; the cleanup job expires it and deletes its objects.
    expiresAt: timestamp({ withTimezone: true }).notNull(),
  },
  (t) => [
    index().on(t.tenantId, t.projectId, t.updatedAt.desc()),
    index().on(t.status, t.expiresAt),
    check('recordings_status', oneOf('status', RECORDING_STATUSES)),
  ],
)

export const DEVICE_COMMAND_KINDS = [
  'tap',
  'long_press',
  'swipe',
  'type',
  'back',
  'home',
  'hide_keyboard',
  'restart_app',
  'prepare',
  'record',
  'inspect',
] as const
export const DEVICE_COMMAND_STATUSES = ['sent', 'ok', 'failed', 'rejected'] as const

/**
 * Audit of every command sent to a device from the browser (FR-009). `params` never holds typed
 * text — only its length, and the secret's name for a password field (FR-014).
 */
export const deviceCommands = pgTable(
  'device_commands',
  {
    id: id(),
    tenantId: tenantId(),
    deviceId: uuid()
      .notNull()
      .references(() => devices.id),
    liveSessionId: uuid().references(() => liveSessions.id),
    recordingId: uuid().references(() => recordings.id),
    userId: uuid()
      .notNull()
      .references(() => users.id),
    kind: text({ enum: DEVICE_COMMAND_KINDS }).notNull(),
    params: jsonb().notNull().default({}),
    status: text({ enum: DEVICE_COMMAND_STATUSES }).notNull().default('sent'),
    error: text(),
    createdAt: createdAt(),
    finishedAt: timestamp({ withTimezone: true }),
  },
  (t) => [
    index().on(t.tenantId, t.deviceId, t.createdAt.desc()),
    check('device_commands_kind', oneOf('kind', DEVICE_COMMAND_KINDS)),
    check('device_commands_status', oneOf('status', DEVICE_COMMAND_STATUSES)),
  ],
)

// ---- Phase 3: Explorer, AI calls and imports (specs/004-phase-3-brain-explorer/data-model.md) ------

/** A screen an exploration met (`explorations.screens`). */
export interface ExplorationScreen {
  fingerprint: string
  id: string
  name: string
  package: string
  activity?: string
  /** Trace step whose `screen.jpg` / `tree.json` picture it. */
  first_step: number
  /** Not in the app map when the exploration started. */
  is_new: boolean
  first_seen_at: string
}

/** One exploration (US2), test-from-prompt (US5) or imported case (US6): lease kind `exploration`. */
export const explorations = pgTable(
  'explorations',
  {
    id: id(),
    tenantId: tenantId(),
    projectId: uuid()
      .notNull()
      .references(() => projects.id),
    appId: uuid()
      .notNull()
      .references(() => apps.id),
    buildId: uuid()
      .notNull()
      .references(() => builds.id),
    deviceId: uuid()
      .notNull()
      .references(() => devices.id),
    userId: uuid()
      .notNull()
      .references(() => users.id),
    leaseId: uuid().references(() => leases.id),
    kind: text({ enum: api.EXPLORATION_KINDS }).notNull(),
    goal: text(),
    budget: jsonb().$type<api.ExplorationBudget>().notNull(),
    maxTests: integer().notNull(),
    status: text({ enum: api.EXPLORATION_STATUSES }).notNull().default('queued'),
    stopReason: text({ enum: api.STOP_REASONS }),
    stats: jsonb().$type<api.ExplorationStats>().notNull().default(api.EMPTY_EXPLORATION_STATS),
    // Screens met so far with their names: the app map is written from them, even after a restart.
    screens: jsonb().$type<ExplorationScreen[]>().notNull().default([]),
    appmapCommit: text(),
    // What the Test writer did with the flows it chose: those left out and why (D48).
    writerReport: jsonb().$type<api.WriterReport>(),
    importItemId: uuid().references((): AnyPgColumn => importItems.id),
    createdAt: createdAt(),
    startedAt: timestamp({ withTimezone: true }),
    finishedAt: timestamp({ withTimezone: true }),
  },
  (t) => [
    index().on(t.tenantId, t.projectId, t.createdAt.desc()),
    index().on(t.status),
    check('explorations_kind', oneOf('kind', api.EXPLORATION_KINDS)),
    check('explorations_status', oneOf('status', api.EXPLORATION_STATUSES)),
    check('explorations_stop_reason', nullOrOneOf('stop_reason', api.STOP_REASONS)),
    check(
      'explorations_max_tests',
      sql`${t.maxTests} between 1 and ${sql.raw(String(api.MAX_TESTS_LIMIT))}`,
    ),
  ],
)

/** The trace: one row per AI decision, refusal, handled popup or restart (research R5). */
export const explorationSteps = pgTable(
  'exploration_steps',
  {
    id: id(),
    tenantId: tenantId(),
    explorationId: uuid()
      .notNull()
      .references(() => explorations.id, { onDelete: 'cascade' }),
    n: integer().notNull(),
    segment: integer().notNull(),
    fingerprint: text().notNull(),
    screenId: text(),
    decision: jsonb().$type<unknown>(),
    status: text({ enum: api.EXPLORATION_STEP_STATUSES }).notNull(),
    refusal: text({ enum: api.STEP_REFUSALS }),
    step: jsonb().$type<unknown>(),
    // What `record` suggested to expect after the step (the Recorder's, no AI): the writer's candidates.
    suggestions: jsonb().$type<unknown[]>().notNull().default([]),
    flags: emptyArray().$type<api.StepFlag[]>(),
    artifactPrefix: text(),
    brainCallId: uuid().references((): AnyPgColumn => brainCalls.id),
    costUsd: usd(),
    createdAt: createdAt(),
  },
  (t) => [
    uniqueIndex().on(t.explorationId, t.n),
    check('exploration_steps_status', oneOf('status', api.EXPLORATION_STEP_STATUSES)),
    check('exploration_steps_refusal', nullOrOneOf('refusal', api.STEP_REFUSALS)),
    check('exploration_steps_flags', allOf('flags', api.STEP_FLAGS)),
  ],
)

/** A crash or ANR met while exploring: a bug candidate for Phase 4. */
export const findings = pgTable(
  'findings',
  {
    id: id(),
    tenantId: tenantId(),
    projectId: uuid()
      .notNull()
      .references(() => projects.id),
    explorationId: uuid()
      .notNull()
      .references(() => explorations.id, { onDelete: 'cascade' }),
    stepN: integer().notNull(),
    kind: text({ enum: api.FINDING_KINDS }).notNull(),
    logExcerpt: text().notNull().default(''),
    artifactPrefix: text(),
    createdAt: createdAt(),
  },
  (t) => [index().on(t.explorationId), check('findings_kind', oneOf('kind', api.FINDING_KINDS))],
)

/** One attempt to call a provider (fallback and re-asks each add a row); content kept 30 days. */
export const brainCalls = pgTable(
  'brain_calls',
  {
    id: id(),
    tenantId: tenantId(),
    role: text({ enum: api.BRAIN_CALL_ROLES }).notNull(),
    provider: text().notNull(),
    model: text().notNull(),
    attempt: integer().notNull(),
    tokensIn: integer().notNull().default(0),
    tokensOut: integer().notNull().default(0),
    tokensCached: integer().notNull().default(0),
    costUsd: usd(),
    latencyMs: integer().notNull().default(0),
    ok: boolean().notNull(),
    error: text({ enum: api.BRAIN_CALL_ERRORS }),
    refType: text({ enum: api.BRAIN_CALL_REF_TYPES }).notNull(),
    refId: uuid().notNull(),
    contentKey: text(),
    createdAt: createdAt(),
  },
  (t) => [
    // The tenant's cost of a UTC day (daily limit, usage page).
    index().on(t.tenantId, t.createdAt),
    index().on(t.refType, t.refId),
    check('brain_calls_role', oneOf('role', api.BRAIN_CALL_ROLES)),
    check('brain_calls_error', nullOrOneOf('error', api.BRAIN_CALL_ERRORS)),
    check('brain_calls_ref_type', oneOf('ref_type', api.BRAIN_CALL_REF_TYPES)),
    check('brain_calls_attempt', sql`${t.attempt} >= 1`),
  ],
)

/** A tool the AI called — or tried to call and was blocked (SC-003). */
export const toolCalls = pgTable(
  'tool_calls',
  {
    id: id(),
    tenantId: tenantId(),
    brainCallId: uuid()
      .notNull()
      .references(() => brainCalls.id, { onDelete: 'cascade' }),
    mcpServer: text().notNull(),
    tool: text().notNull(),
    argsRedacted: jsonb().$type<unknown>().notNull().default({}),
    ok: boolean().notNull(),
    blocked: boolean().notNull().default(false),
    error: text({ enum: api.TOOL_CALL_ERRORS }),
    latencyMs: integer().notNull().default(0),
    createdAt: createdAt(),
  },
  (t) => [
    index().on(t.brainCallId),
    check('tool_calls_error', nullOrOneOf('error', api.TOOL_CALL_ERRORS)),
  ],
)

/** Manual test cases imported from a file (US6); each case runs as a `kind = import` exploration. */
export const importJobs = pgTable(
  'import_jobs',
  {
    id: id(),
    tenantId: tenantId(),
    projectId: uuid()
      .notNull()
      .references(() => projects.id),
    appId: uuid().references(() => apps.id),
    buildId: uuid().references(() => builds.id),
    deviceId: uuid().references(() => devices.id),
    createdBy: uuid()
      .notNull()
      .references(() => users.id),
    sourceFormat: text({ enum: IMPORT_FORMATS }).notNull(),
    fileName: text().notNull(),
    // The XLSX sheet read; the uploaded file is kept until the job ends (data-model §5).
    sheet: text(),
    mapping: jsonb().$type<unknown>(),
    status: text({ enum: api.IMPORT_JOB_STATUSES }).notNull().default('preview'),
    budget: jsonb().$type<api.ImportBudget>(),
    stats: jsonb().$type<api.ImportStats>().notNull().default(api.EMPTY_IMPORT_STATS),
    report: jsonb().$type<api.ImportReport>(),
    manualCommit: text(),
    createdAt: createdAt(),
    startedAt: timestamp({ withTimezone: true }),
    finishedAt: timestamp({ withTimezone: true }),
  },
  (t) => [
    index().on(t.tenantId, t.projectId, t.createdAt.desc()),
    index().on(t.status),
    check('import_jobs_source_format', oneOf('source_format', IMPORT_FORMATS)),
    check('import_jobs_status', oneOf('status', api.IMPORT_JOB_STATUSES)),
  ],
)

export const importItems = pgTable(
  'import_items',
  {
    id: id(),
    tenantId: tenantId(),
    importJobId: uuid()
      .notNull()
      .references(() => importJobs.id, { onDelete: 'cascade' }),
    n: integer().notNull(),
    manualPath: text().notNull(),
    title: text().notNull(),
    status: text({ enum: api.IMPORT_ITEM_STATUSES }).notNull().default('pending'),
    reason: text({ enum: api.IMPORT_ITEM_REASONS }),
    evidence: jsonb().$type<{ step_n?: number; artifact_prefix?: string; message: string }>(),
    explorationId: uuid().references((): AnyPgColumn => explorations.id),
    testCaseId: uuid().references(() => testCases.id),
    costUsd: usd(),
    updatedAt: timestamp({ withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex().on(t.importJobId, t.n),
    check('import_items_status', oneOf('status', api.IMPORT_ITEM_STATUSES)),
    check('import_items_reason', nullOrOneOf('reason', api.IMPORT_ITEM_REASONS)),
  ],
)

/** Tables that must carry tenant_id (P5); used by the schema test. */
export const BUSINESS_TABLES = [
  'memberships',
  'projects',
  'apps',
  'builds',
  'agents',
  'devices',
  'leases',
  'test_cases',
  'project_files',
  'runs',
  'run_items',
  'run_steps',
  'audit_log',
  'live_sessions',
  'recordings',
  'device_commands',
  'explorations',
  'exploration_steps',
  'findings',
  'brain_calls',
  'tool_calls',
  'import_jobs',
  'import_items',
] as const
